from smartfast.exceptions import SmartfastException


class SmartIRError(SmartfastException):
    pass
